### ISSUE TITLE
Please stop the `warn` spam

### ISSUE THREAD

**Issue by grosser** [liufengyun/hashdiff#66]
now every test run/boot has a warning :(
Just remove the constant and be done with it ... or do whatever activesupport does but only when a deprecated constant is used

caused by https://github.com/liufengyun/hashdiff/pull/65

**Comment by jfelchner** [comment]
"spam" is something that is uselss.  Warning users about a deprecation is not useless.  Is it intrusive?  Yes.  Is it a potentially huge issue if people don't update their constants before they upgrade?  Also yes.

The warning intrusion is in proportion to the impact of not heeding it.

**Comment by grosser** [comment]
Warnings I cannot do anything and already know about, are spam for me.
Whoever depends on version `>=0` should be prepared for things to break,
using `~> 0.3` would be safe.

To reduce blast-radius: see which gems depend on hashdiff and reach out to
them, whoever uses it in their tests directly should see the blow-up
To warn on use: define a proxy with the old name and use method_missing to
warn+delegate

**Comment by grosser** [comment]
thx for being so careful though, I did not know what depends on this gem ... I just use it for some api diffing tools :)

**Comment by jfelchner** [comment]
@grosser I completely agree.  And we _have_ reached out to gems that use this gem.  Specifically the biggest one: `webmock`.  But we can't be assured that we're going to get them all, hence the warning is still necessary.

`webmock` has always had an open-ended dependency on `hashdiff` (`> 0.0`) which means that we needed the warning in case there was any weird old combination of versions with old webmock installs.

I have PRs that should patch `webmock` versions 1.x, 2.x, and 3.x.  Once those are in, we'll release a v1 of `hashdiff` and the warnings should go away for everyone.

A proxy would definitely work but is also potentially more error-prone.  Because `webmock` is such a popular gem, I didn't want to take the chance that an error in the proxy implementation (no matter how simple a `method_missing` would be) would cause every one of the millions of `webmock` installs to fail.

**Comment by grosser** [comment]
Sounds like you are having a good time, good luck :D

**Comment by liufengyun** [comment]
Thank you all @jfelchner @grosser @krzysiek1507 , I close the PR then.
